### PR TITLE
Adding a delete button for Task and Batch List/Delete in Scan Page

### PR DESCRIPTION
**Pull request by azenko**
I've added a delete button in the Progress page to delete a old task.
Things who left to do : Remove the result of the Task from the
visualization.

### CODE REVIEW

**Comment by fschwebel** [comment]
Does that work if the batch is still being completed by the scanner?

**Comment by azenko** [comment]
The task is deleted in the database and same for the line in the Progress page, but the result is still accessible in visualization.

**Comment by azenko** [comment]
I have add a Batch List and a Deleting Function for Batch in the Batch list on the Scan Page.

**Comment by azenko** [comment]
Voila j'ai fini de rajouter le scan des chaines de caractères et des md5, tout fonctionne avec.

**Pull request closed without merging**
